name: Build Core

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout.'
        required: true
        default: 'support-cloudgame'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
          show-progress: false

      - name: Set tag
        id: set_tag
        run: |
          # 尝试获取 tag，失败则使用 short sha
          tag=$(git describe --tags --match "v*" 2>/dev/null || echo "v0.0.1-$(git rev-parse --short HEAD)")
          echo "tag=${tag}" | tee -a $GITHUB_OUTPUT

  windows-core:
    needs: meta
    strategy:
      matrix:
        arch: [x64]
      fail-fast: false
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.ref }}
          show-progress: false

      - name: Fetch submodules
        run: |
          # 必须初始化 MaaUtils
          git submodule update --init --depth 1 src/MaaUtils
          git submodule update --init --depth 1 3rdparty/EmulatorExtras

      - name: Cache MaaDeps
        id: cache-maadeps
        uses: actions/cache@v5
        with:
          # 注意：现在的路径在 src/MaaUtils 下
          path: ./src/MaaUtils/MaaDeps
          key: ${{ runner.os }}-${{ matrix.arch }}-maadeps-${{ hashFiles('tools/maadeps-download.py') }}

      - name: Bootstrap MaaDeps
        if: steps.cache-maadeps.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 tools/maadeps-download.py ${{ matrix.arch }}-windows

      - name: Config cmake
        run: |
          mkdir -p build
          # 补充了官方现在要求的 DINSTALL_RESOURCE 和 DINSTALL_PYTHON
          cmake -B build `
            ${{ matrix.arch == 'arm64' && '-A ARM64' || '' }} `
            -DCMAKE_BUILD_TYPE=RelWithDebInfo `
            -DMAADEPS_TRIPLET='maa-${{ matrix.arch }}-windows' `
            -DINSTALL_RESOURCE=ON `
            -DINSTALL_PYTHON=ON `
            -DMAA_HASH_VERSION='${{ needs.meta.outputs.tag }}' `
            -DBUILD_WPF_GUI=OFF

      - name: Build MaaCore
        run: |
          # 编译全部（由于只有 Core 及其依赖，所以不会编译 GUI）
          cmake --build build --config RelWithDebInfo --parallel $env:NUMBER_OF_PROCESSORS

      - name: Install
        run: |
          # 使用 install 自动收集所有必须的 DLL (MaaCore.dll, MaaUtils.dll, opencv_world.dll 等)
          cmake --install build --prefix install --config RelWithDebInfo

      - name: Upload Core Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: MAA-Core-win-${{ matrix.arch }}
          path: install/bin/
