name: Build Core

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout.'
        required: true
        default: 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0 # Fetch all history for git describe
          show-progress: false

      - name: Set tag
        id: set_tag
        run: |
          echo tag=$(git describe --tags --match "v*" || git rev-parse --short HEAD) | tee -a $GITHUB_OUTPUT

  windows-core:
    needs: meta
    strategy:
      matrix:
        arch: [x64]
      fail-fast: false
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.ref }}
          show-progress: false

      - name: Fetch submodules
        run: |
          git submodule update --init --depth 1 3rdparty/EmulatorExtras

      - name: Cache MaaDeps
        id: cache-maadeps
        uses: actions/cache@v4
        with:
          path: ./MaaDeps
          key: ${{ runner.os }}-${{ matrix.arch }}-maadeps-${{ hashFiles('tools/maadeps-download.py') }}

      - name: Bootstrap MaaDeps
        if: steps.cache-maadeps.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 tools/maadeps-download.py ${{ matrix.arch }}-windows

      - name: Config cmake
        run: |
          mkdir -p build
          cmake -B build ${{ matrix.arch == 'arm64' && '-A ARM64' }} -DCMAKE_BUILD_TYPE=Release -DMAADEPS_TRIPLET='maa-${{ matrix.arch }}-windows' -DMAA_HASH_VERSION='${{ needs.meta.outputs.tag }}' -DBUILD_WPF_GUI=OFF

      - name: Build MaaCore
        run: |
          cmake --build build --config Release --parallel $env:NUMBER_OF_PROCESSORS --target MaaCore

      - name: Upload MaaCore.dll
        uses: actions/upload-artifact@v4
        with:
          name: MAA-win-${{ matrix.arch }}
          path: build/bin/Release/MaaCore.dll
